# Generated by Django 2.2 on 2019-09-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=50, verbose_name='Имя автора')),
                ('email', models.EmailField(max_length=70, verbose_name='email автора')),
                ('text', models.TextField(max_length=1500, verbose_name='Текст записи')),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
                ('LastEditDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'активно'), ('blocked', 'заблокировано')], default='active', max_length=40, verbose_name='Статус')),
            ],
        ),
    ]
